//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StegBMP.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StegBMP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   抽出 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BUTTONTEXT_EXTRACT {
            get {
                return ResourceManager.GetString("BUTTONTEXT_EXTRACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   抽出中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BUTTONTEXT_EXTRACTING {
            get {
                return ResourceManager.GetString("BUTTONTEXT_EXTRACTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   書込 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BUTTONTEXT_WRITE {
            get {
                return ResourceManager.GetString("BUTTONTEXT_WRITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   書込中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BUTTONTEXT_WRITING {
            get {
                return ResourceManager.GetString("BUTTONTEXT_WRITING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   抽出完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CAPTION_EXTRACTING_SUCCEEDED {
            get {
                return ResourceManager.GetString("CAPTION_EXTRACTING_SUCCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルが開かれています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CAPTION_FILE_ALREADY_OPENED {
            get {
                return ResourceManager.GetString("CAPTION_FILE_ALREADY_OPENED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   存在しないファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CAPTION_FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("CAPTION_FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不正な拡張子 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CAPTION_INVALID_EXTENTION {
            get {
                return ResourceManager.GetString("CAPTION_INVALID_EXTENTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不正な画像ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CAPTION_INVALID_IMAGE_TYPE {
            get {
                return ResourceManager.GetString("CAPTION_INVALID_IMAGE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   記録容量不足 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CAPTION_TOO_LARGE_FILE {
            get {
                return ResourceManager.GetString("CAPTION_TOO_LARGE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   原因不明のエラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CAPTION_UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("CAPTION_UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   書込完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CAPTION_WRITING_SUCCEEDED {
            get {
                return ResourceManager.GetString("CAPTION_WRITING_SUCCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名無し に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DEFAULT_FILE_NAME {
            get {
                return ResourceManager.GetString("DEFAULT_FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}がnullです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FORMATED_MESSAGE_IS_NULL {
            get {
                return ResourceManager.GetString("FORMATED_MESSAGE_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルの抽出先のフォルダを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESSAGE_DIRECTORY_SELECT_DIALOG {
            get {
                return ResourceManager.GetString("MESSAGE_DIRECTORY_SELECT_DIALOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   下の白い領域にファイル（複数可）をドラッグしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESSAGE_DRAG_FILES_HERE {
            get {
                return ResourceManager.GetString("MESSAGE_DRAG_FILES_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   抽出中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESSAGE_EXTRACTING {
            get {
                return ResourceManager.GetString("MESSAGE_EXTRACTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   抽出が完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESSAGE_EXTRACTING_SUCCEEDED {
            get {
                return ResourceManager.GetString("MESSAGE_EXTRACTING_SUCCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   書込先のファイルが既に開かれており，書込を行えません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESSAGE_FILE_ALREADY_OPENED {
            get {
                return ResourceManager.GetString("MESSAGE_FILE_ALREADY_OPENED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルの保存先のフォルダを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESSAGE_FILE_SAVE_DIALOG {
            get {
                return ResourceManager.GetString("MESSAGE_FILE_SAVE_DIALOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   この画像ファイルには以下のファイルが記録されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESSAGE_IMAGE_INCLUDE_THESE_FILES {
            get {
                return ResourceManager.GetString("MESSAGE_IMAGE_INCLUDE_THESE_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルの拡張子が不正です。ドロップできるファイルの拡張子は .bmp .jpg .png .tiff のいずれかです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESSAGE_INVALID_EXTENTION {
            get {
                return ResourceManager.GetString("MESSAGE_INVALID_EXTENTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BMPファイル，PNGファイル，TIFFファイル，JPGファイルのいずれかをドロップできます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESSAGE_INVALID_IMAGE_TYPE {
            get {
                return ResourceManager.GetString("MESSAGE_INVALID_IMAGE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   「書込」ボタンを押すとファイルの書込を開始します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESSAGE_READY_TO_WRITE_DATA {
            get {
                return ResourceManager.GetString("MESSAGE_READY_TO_WRITE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルサイズが大きすぎます。記録容量が足りません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESSAGE_TOO_LARGE_FILE {
            get {
                return ResourceManager.GetString("MESSAGE_TOO_LARGE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   記録容量が足りません。（データ秘匿レベルを高くするほど記録容量が減ります。） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESSAGE_TOO_LARGE_FILE_WITH_ADVICE {
            get {
                return ResourceManager.GetString("MESSAGE_TOO_LARGE_FILE_WITH_ADVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   原因不明のエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESSAGE_UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("MESSAGE_UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   書き込み中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESSAGE_WRITING {
            get {
                return ResourceManager.GetString("MESSAGE_WRITING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   書込が完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MESSAGE_WRITING_SUCCEEDED {
            get {
                return ResourceManager.GetString("MESSAGE_WRITING_SUCCEEDED", resourceCulture);
            }
        }
    }
}
